version: '3'

services:
  web:
    image: nginx:stable-alpine
    volumes:
      - .:/var/www
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - docker_network
      - docker_proxy
    environment:
        - VIRTUAL_HOST=netdev.alien-panic.co.uk
    restart: unless-stopped
  app:
    image: alienpanic-app
    container_name: alienpanic-app
    hostname: alienpanic-app
    build:
      context: .docker/php
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - docker_network
      - docker_proxy
    restart: unless-stopped
  composer:
    image: alienpanic-composer
    container_name: alienpanic-composer
    build:
      context: .docker/composer
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    networks:
      - docker_network
      - docker_proxy
  assets:
    image: node:12
    volumes:
      - .:/app
    working_dir: /app
networks:
  docker_network:
    driver: bridge
  docker_proxy:
    external:
      name: docker-proxy
